<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace Group\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Group.Protocol.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     */
    protected $contentType = '';
    /**
     * Generated from protobuf field <code>string cmd = 3;</code>
     */
    protected $cmd = '';
    /**
     * Generated from protobuf field <code>repeated string cmds = 4;</code>
     */
    private $cmds;
    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $contentType
     *     @type string $cmd
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $cmds
     *     @type \Group\Protocol\Data $data
     * }
     */
    public function __construct($data = NULL) {
        \Group\Protocol\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->contentType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cmd = 3;</code>
     * @return string
     */
    public function getCmd()
    {
        return $this->cmd;
    }

    /**
     * Generated from protobuf field <code>string cmd = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCmd($var)
    {
        GPBUtil::checkString($var, True);
        $this->cmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string cmds = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCmds()
    {
        return $this->cmds;
    }

    /**
     * Generated from protobuf field <code>repeated string cmds = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCmds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cmds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     * @return \Group\Protocol\Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     * @param \Group\Protocol\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Group\Protocol\Data::class);
        $this->data = $var;

        return $this;
    }

}

