<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

namespace Group\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Group.Protocol.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string version = 1;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     */
    protected $contentType = '';
    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string errMsg = 4;</code>
     */
    protected $errMsg = '';
    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *     @type string $contentType
     *     @type int $code
     *     @type string $errMsg
     *     @type \Group\Protocol\Data $data
     * }
     */
    public function __construct($data = NULL) {
        \Group\Protocol\GPBMetadata\Request::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->contentType;
    }

    /**
     * Generated from protobuf field <code>string contentType = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->contentType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string errMsg = 4;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->errMsg;
    }

    /**
     * Generated from protobuf field <code>string errMsg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->errMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     * @return \Group\Protocol\Data
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.Group.Protocol.Data data = 5;</code>
     * @param \Group\Protocol\Data $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Group\Protocol\Data::class);
        $this->data = $var;

        return $this;
    }

}

