#!/usr/bin/env php
<?php

use Group\Sync\Sync;
use Group\Sync\SyncApp;

define('ASYNC', false);

//发布时候路径问题
if (file_exists("runtime/webroot")) {
    $webroot = file_get_contents("../runtime/webroot");
    define('__FILEROOT__', $webroot . DIRECTORY_SEPARATOR);
} else {
    define('__FILEROOT__', realpath(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "../");
}

$loader = require __FILEROOT__.'vendor/autoload.php';

$app = new SyncApp();
$app -> initSelf();
$provider = new Group\Sync\Cache\FileCacheServiceProvider($app::getInstance());
$provider -> register();

$async = new Sync($argv);
$async -> run();
