<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace Group\Protocol\GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a0e726573706f6e73652e70726f746f120e47726f75702e50726f746f636f6c225c0a08526573706f6e7365120f0a0776657273696f6e18012001280912130a0b636f6e74656e7454797065180220012809120c0a04636f6465180320012805120e0a066572724d7367180420012809120c0a0464617461180520012809421de2021a47726f75705c50726f746f636f6c5c4750424d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

